// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestDatHangTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testDatHang() {
    driver.Navigate().GoToUrl("http://localhost:63565/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.LinkText("Xem chi tiết")).Click();
    driver.FindElement(By.LinkText("THÊM VÀO GIỎ HÀNG")).Click();
    driver.FindElement(By.CssSelector(".nav-item > .nav-link > span")).Click();
    driver.FindElement(By.CssSelector(".fa-money-bill-wave")).Click();
    driver.FindElement(By.Id("txtHoTen")).SendKeys("Từ Huệ Sơn");
    driver.FindElement(By.Id("txtEmail")).SendKeys("tuhueson@gmail");
    driver.FindElement(By.Id("txtSDT")).SendKeys("0938252793");
    driver.FindElement(By.Id("txtDiaChi")).SendKeys("140 Lê Trọng Tân");
    {
      var dropdown = driver.FindElement(By.Id("TinhThanh"));
      dropdown.FindElement(By.XPath("//option[. = 'Đà Nẵng']")).Click();
    }
    {
      var dropdown = driver.FindElement(By.Id("QuanHuyen"));
      dropdown.FindElement(By.XPath("//option[. = 'Quận Cẩm Lệ']")).Click();
    }
    {
      var dropdown = driver.FindElement(By.Id("XaPhuong"));
      dropdown.FindElement(By.XPath("//option[. = 'Phường Hoà Thọ Đông']")).Click();
    }
    driver.FindElement(By.Id("btnXacNhan")).Click();
    Assert.That(driver.FindElement(By.Id("swal2-title")).Text, Is.EqualTo("Email không hợp lệ.Vui lòng nhập lại."));
    driver.FindElement(By.CssSelector(".nav-item > .nav-link > span")).Click();
    driver.FindElement(By.CssSelector(".fa-trash-alt")).Click();
    Assert.That(driver.FindElement(By.CssSelector("#tenKhachHang")).Text, Is.Not.EqualTo(" "));
  }
}
