// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestDangKy
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver(@"D:\github\webBanMyPham\Test");
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    public void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void dangKy()
    {
        driver.Navigate().GoToUrl("http://localhost:63565/Auth/DangNhap");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
        driver.FindElement(By.LinkText("ĐĂNG KÝ")).Click();
        driver.FindElement(By.Id("floatingNameSignup")).SendKeys("Từ Huệ Sơn");
        driver.FindElement(By.Id("floatingUsernameSignup")).SendKeys("tuhueson");
        driver.FindElement(By.Id("floatingPasswordSignup")).SendKeys("123456789");
        driver.FindElement(By.Id("floatingEmailSignup")).SendKeys("tuhueson@gmail.com");
        driver.FindElement(By.Id("floatingNgSinhSignup")).SendKeys("2022-05-26");
        driver.FindElement(By.Id("floatingPhoneSignup")).SendKeys("0938252793");
        driver.FindElement(By.Id("btnSignupInfo")).Click();
        try
        {
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10); 
            Assert.That(driver.FindElement(By.Id("swal2-title")).Text, Is.EqualTo("Username đã tồn tại. Vui lòng nhập lại"));
        }
        catch (Exception)
        {

            throw;
        }
    }
    [Test]
    public void dangKy(string pUsername, string pHoTen, string pPw, string pEmail, string pNgaySinh, string pSDT, string pKetQuaMongMuon)
    {
        driver.Navigate().GoToUrl("http://localhost:63565/");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
        driver.FindElement(By.LinkText("ĐĂNG KÝ")).Click();
        driver.FindElement(By.Id("floatingNameSignup")).SendKeys(pHoTen);
        driver.FindElement(By.Id("floatingUsernameSignup")).SendKeys(pUsername);
        driver.FindElement(By.Id("floatingPasswordSignup")).SendKeys(pPw);
        driver.FindElement(By.Id("floatingEmailSignup")).SendKeys(pEmail);
        driver.FindElement(By.Id("floatingNgSinhSignup")).SendKeys(pNgaySinh);
        driver.FindElement(By.Id("floatingPhoneSignup")).SendKeys(pSDT);
        driver.FindElement(By.Id("btnSignupInfo")).Click();

        Thread.Sleep(1000);

        try
        {
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(20);
            Assert.That(driver.FindElement(By.Id("swal2-title")).Text, Is.EqualTo(pKetQuaMongMuon));
        }
        catch (Exception er)
        {
            throw;
        }
        finally
        {
            TearDown();
        }
    }
}
